###
PUT http://localhost:8080/account
Content-Type: application/json


{
 "name": "xaxa",
 "number": 2,
 "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}

###
PUT http://localhost:8080/account
Content-Type: application/json


{
  "name": "xaxa",
  "number": 2,
  "operation": 100
}


